
import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/widgets/header'
import { Footer } from '@/widgets/footer'
import { ThemeProvider } from './themeProvider'
import { useTheme } from "next-themes"
import { Toaster } from '@/shared/shadcn/ui/toaster'
import { RecoilRoot } from 'recoil'
import RecoilRootWrapper from './recoilWrapper'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  return (
    <html lang="ko">
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
        <Header />
        <RecoilRootWrapper>{children}</RecoilRootWrapper>
      </ThemeProvider>
      <Toaster />
      </body>
    </html>
  )
}
